---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notebook-ingress
  namespace: istio-system
spec:
  ingressClassName: tmax-cloud
  rules:
  - host: console.{{ custom_domain_name }}
    http:
      paths:
      - backend:
          serviceName: istio-ingressgateway
          servicePort: 80 
        path: /api/kubeflow/notebook/
        pathType: Prefix
  tls:
  - hosts:
    - console.{{ custom_domain_name }}
