apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: demo-inferenceservice
  namespace: demo
spec:
  predictor:
  ## inference server 정의
    tensorflow:      
      ## Model 위치 설정
      storageUri: pvc://demo-pvc/saved_model