apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fmnistpipeline
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"echo": [], "fmnist": [], "kfserving": [], "list-list":
      []}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"description": "mnist", "inputs": [{"name":
      "learning_rate"}, {"name": "dropout_rate"}, {"name": "epoch"}, {"name": "act"},
      {"name": "layer"}, {"name": "checkpoint_dir"}, {"name": "saved_model_dir"},
      {"name": "pvc_name"}, {"name": "tensorboard_log"}, {"name": "name"}, {"name":
      "model_version"}, {"name": "namespace"}], "name": "FMnistPipeline"}'
spec:
  params:
  - {name: learning_rate, value: '0.001397'}
  - {name: dropout_rate, value: '0.18'}
  - {name: epoch, value: '11'}
  - {name: act, value: 'sigmoid'}
  - {name: layer, value: '2'}
  - {name: checkpoint_dir, value: '/result/training_checkpoints'}
  - {name: saved_model_dir, value: '/result/saved_model/'}
  - {name: pvc_name, value: 'demo-pvc'}
  - {name: tensorboard_log, value: '/result/log'}
  - {name: name, value: 'kfserving-fmnist'}
  - {name: model_version, value: '0001'}
  - {name: namespace, value: 'demo'}
  pipelineSpec:
    params:
    - {name: learning_rate}
    - {name: dropout_rate}
    - {name: epoch}
    - {name: act}
    - {name: layer}
    - {name: checkpoint_dir}
    - {name: saved_model_dir}
    - {name: pvc_name}
    - {name: tensorboard_log}
    - {name: name}
    - {name: model_version}
    - {name: namespace}
    tasks:
    - name: fmnist
      params:
      - {name: act, value: $(params.act)}
      - {name: checkpoint_dir, value: $(params.checkpoint_dir)}
      - {name: dropout_rate, value: $(params.dropout_rate)}
      - {name: epoch, value: $(params.epoch)}
      - {name: layer, value: $(params.layer)}
      - {name: learning_rate, value: $(params.learning_rate)}
      - {name: model_version, value: $(params.model_version)}
      - {name: pvc_name, value: $(params.pvc_name)}
      - {name: saved_model_dir, value: $(params.saved_model_dir)}
      - {name: tensorboard_log, value: $(params.tensorboard_log)}
      taskSpec:
        steps:
        - name: main
          args: [--learning_rate, $(inputs.params.learning_rate), --dropout_rate,
            $(inputs.params.dropout_rate), --epoch, $(inputs.params.epoch), --act,
            $(inputs.params.act), --layer, $(inputs.params.layer), --checkpoint_dir,
            $(inputs.params.checkpoint_dir), --saved_model_dir, $(inputs.params.saved_model_dir),
            --model_version, $(inputs.params.model_version), --tensorboard_log, $(inputs.params.tensorboard_log)]
          command: [python, /app/fmnist-save-model-renew.py]
          image: rhojw/katib-job:8E825523
          volumeMounts:
          - {mountPath: /result, name: pvolume-e819e39f92a888af338a32082ea85feaa488e4a0aabfacc858d718b}
        params:
        - {name: act}
        - {name: checkpoint_dir}
        - {name: dropout_rate}
        - {name: epoch}
        - {name: layer}
        - {name: learning_rate}
        - {name: model_version}
        - {name: pvc_name}
        - {name: saved_model_dir}
        - {name: tensorboard_log}
        volumes:
        - name: pvolume-e819e39f92a888af338a32082ea85feaa488e4a0aabfacc858d718b
          persistentVolumeClaim: {claimName: $(inputs.params.pvc_name)}
      timeout: 0s
    - name: list-list
      params:
      - {name: pvc_name, value: $(params.pvc_name)}
      taskSpec:
        steps:
        - name: main
          command: [ls, -R, /result]
          image: library/bash:4.4.23
          volumeMounts:
          - {mountPath: /result, name: pvolume-e819e39f92a888af338a32082ea85feaa488e4a0aabfacc858d718b}
        params:
        - {name: pvc_name}
        volumes:
        - name: pvolume-e819e39f92a888af338a32082ea85feaa488e4a0aabfacc858d718b
          persistentVolumeClaim: {claimName: $(inputs.params.pvc_name)}
      runAfter: [fmnist, fmnist]
      timeout: 0s
    - name: kfserving
      params:
      - {name: name, value: $(params.name)}
      - {name: namespace, value: $(params.namespace)}
      - {name: pvc_name, value: $(params.pvc_name)}
      taskSpec:
        steps:
        - name: main
          args: [--namespace, $(inputs.params.namespace), --storage_uri, 'pvc://$(inputs.params.pvc_name)/saved_model',
            --name, $(inputs.params.name)]
          command: [python, /app/KFServing-fairing.py]
          image: rhojw/kfserving:6962115B
        params:
        - {name: name}
        - {name: namespace}
        - {name: pvc_name}
      runAfter: [list-list]
      timeout: 0s
    finally:
    - name: echo
      taskSpec:
        steps:
        - name: main
          args: [echo "$0", Done!]
          command: [sh, -c]
          image: library/bash:4.4.23
      timeout: 0s
  timeout: 0s
