apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: fmnistpipeline
  annotations:
    tekton.dev/output_artifacts: '{}'
    tekton.dev/input_artifacts: '{}'
    tekton.dev/artifact_bucket: mlpipeline
    tekton.dev/artifact_endpoint: minio-service.kubeflow:9000
    tekton.dev/artifact_endpoint_scheme: http://
    tekton.dev/artifact_items: '{"echo": [], "fmnist": [], "kfserving": [], "list-list":
      []}'
    sidecar.istio.io/inject: "false"
    pipelines.kubeflow.org/pipeline_spec: '{"description": "mnist", "inputs": [{"name":
      "learning_rate"}, {"name": "dropout_rate"}, {"name": "epoch"}, {"name": "act"},
      {"name": "layer"}, {"name": "checkpoint_dir"}, {"name": "saved_model_dir"},
      {"name": "pvc_name"}, {"name": "tensorboard_log"}, {"name": "name"}, {"name":
      "model_version"}, {"name": "namespace"}], "name": "FMnistPipeline"}'
spec:
  params:
  - name: learning_rate
    value: ''
  - name: dropout_rate
    value: ''
  - name: epoch
    value: ''
  - name: act
    value: ''
  - name: layer
    value: ''
  - name: checkpoint_dir
    value: ''
  - name: saved_model_dir
    value: ''
  - name: pvc_name
    value: ''
  - name: tensorboard_log
    value: ''
  - name: name
    value: ''
  - name: model_version
    value: ''
  - name: namespace
    value: ''
  pipelineSpec:
    params:
    - name: learning_rate
    - name: dropout_rate
    - name: epoch
    - name: act
    - name: layer
    - name: checkpoint_dir
    - name: saved_model_dir
    - name: pvc_name
    - name: tensorboard_log
    - name: name
    - name: model_version
    - name: namespace
    tasks:
    - name: fmnist
      taskSpec:
        steps:
        - name: main
          args:
          - --learning_rate
          - '0.001397'
          - --dropout_rate
          - '0.18'
          - --epoch
          - '11'
          - --act
          - sigmoid
          - --layer
          - '2'
          - --checkpoint_dir
          - /result/training_checkpoints
          - --saved_model_dir
          - /result/saved_model/
          - --model_version
          - '0001'
          - --tensorboard_log
          - /result/log
          command:
          - python
          - /app/fmnist-save-model-renew.py
          image: rhojw/sample-job:3C8CE2EE
          volumeMounts:
          - mountPath: /result
            name: pvolume-05c5c4b5bf273771eb5cf834db4bf0f1642568810e135c7afcef651
        volumes:
        - name: pvolume-05c5c4b5bf273771eb5cf834db4bf0f1642568810e135c7afcef651
          persistentVolumeClaim:
            claimName: demo-pvc
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      timeout: 0s
    - name: list-list
      taskSpec:
        steps:
        - name: main
          command:
          - ls
          - -R
          - /result
          image: library/bash:4.4.23
          volumeMounts:
          - mountPath: /result
            name: pvolume-05c5c4b5bf273771eb5cf834db4bf0f1642568810e135c7afcef651
        volumes:
        - name: pvolume-05c5c4b5bf273771eb5cf834db4bf0f1642568810e135c7afcef651
          persistentVolumeClaim:
            claimName: demo-pvc
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      runAfter:
      - fmnist
      - fmnist
      timeout: 0s
    - name: kfserving
      taskSpec:
        steps:
        - name: main
          args:
          - --namespace
          - kubeflow
          - --storage_uri
          - pvc://demo-pvc/saved_model
          - --name
          - kfserving-fmnist
          command:
          - python
          - /app/KFServing-fairing.py
          image: rhojw/kfserving:6962115B
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      runAfter:
      - list-list
      timeout: 0s
    finally:
    - name: echo
      taskSpec:
        steps:
        - name: main
          args:
          - echo "$0"
          - Done!
          command:
          - sh
          - -c
          image: library/bash:4.4.23
        metadata:
          labels:
            pipelines.kubeflow.org/pipelinename: ''
            pipelines.kubeflow.org/generation: ''
            pipelines.kubeflow.org/cache_enabled: "true"
          annotations:
            tekton.dev/template: ''
      timeout: 0s
  timeout: 0s

