apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "demo-tfjob"
  namespace: demo
spec:
  cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: rhojw/sample-job:3C8CE2EE
              command:
                - "python"
                - "/app/fmnist-save-model-renew.py"
                - "--log_dir=/train/logs"
                - "--learning_rate=0.01"
                - "--batch_size=150"
              volumeMounts:
                - mountPath: "/train"
                  name: "training"
          volumes:
            - name: "training"
              persistentVolumeClaim:
                claimName: "tfevent-volume"
