apiVersion: "serving.kubeflow.org/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "cifar10"
  namespace: mms
spec:
  inferenceService: triton-mms
  model:
    framework: pytorch
    storageUri: "s3://triton/torchscript/cifar10"
